name: frontend
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^1.0.0
  google_maps_flutter: ^0.5.26
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  permission_handler: ^4.0.0
  contacts_service: ^0.3.10
  location: any
  http: ^0.12.0+4
  google_map_polyline: ^0.2.0+1
  flutter_polyline_points: ^0.1.0
  pin_input_text_field: ^3.0.1
  pin_code_fields: ^2.5.1
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  flutter_facebook_login: 
  intro_slider: ^2.2.9
  google_sign_in: ^4.4.3
  mapbox_gl: ^0.0.5
  flutter_map: any
  provider: ^3.1.0
  geolocator: ^5.3.1
  geolocation: ^1.1.2
  user_location: any
  mapbox_search_flutter: any
  color: any
  mapbox_search: any
  requests: ^3.1.0
  polygon_clipper: ^1.0.2
  flutter_custom_clippers: ^1.1.1
  numberpicker: ^1.2.0
  flutter_mapbox_navigation: ^0.0.10
  carousel_pro: ^1.0.0
  map_controller: any
  geojson: any 
  bordered_text: ^1.0.0

  
dev_dependencies:
  flutter_config: ^1.0.7
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - logo.png
   - mapPlaceholder.png
   - googleLoginMini.png
   - backgroundStockholm.png
   - SafeLightLogo.png
   - logophase4png.png
   - profilePH.png
   - photo_eraser.png
   - photo_pencil.png
   - photo_ruler.png
   - DogBackground.jpg
   - Bellevueparken.jpg
   - BrewDog.jpg
   - BrommaKyrka.jpg
   - DogBakery.jpg
   - hundrastgard-henriksdal.jpg
   - Hundoarna.jpg
   - Langholmen.jpg
   - ormingesHundrastgard.jpg
   - Valdemarsudde.jpg
   - AkersbergasHundpark.jpg
   - LeBistro.jpg
   - HimmelskaHundar.jpg
   - DogLogo.png
   - emailicon40pxl.png
   - facebookicon.png
   - logoproject2.png
   - facebookicon40pxl.png
   - googleicon40pxl.png
   - logolightpink.png
   - logocolorpurpleback.png
   - emailicon100pxl.png
   - googleicon144pxl.png
   - facebookicon140pxl.png
   - logonavy.png
   - logogreen.png
   - logopurplepink.png
   - fakefeed.png
   - blind.png
   - pin.png

   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
