package com.example.backend;

import java.util.HashSet;
import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import antlr.collections.List;

import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/contacts")
public class ContactRequestController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path = "/sentRequests")
    public @ResponseBody Set<ContactRequest> getContactRequests(@RequestParam String uid) {
        Set<ContactRequest> sent = new HashSet<ContactRequest>();
        Set<ContactRequest> list = userRepository.findByUid(uid).getContactRequest();
        User user = userRepository.findByUid(uid);
        for (ContactRequest e : list) {

            if(e.getSender() != null && e.getSender().getUid() == user.getUid()){
                sent.add(e);
            }

        }
        return sent;
    }
    @GetMapping(path = "/waitingRequests")
    public @ResponseBody Set<ContactRequest> getWaitingContactRequests(@RequestParam String uid) {
        Set<ContactRequest> sent = new HashSet<ContactRequest>();
        Set<ContactRequest> list = userRepository.findByUid(uid).getContactRequest();
        User user = userRepository.findByUid(uid);
        for (ContactRequest e : list) {

            if(e.getSender() != null && e.getSender().getUid() != user.getUid()){
                sent.add(e);
            }

        }
        return sent;
    }


    @PostMapping(path = "/answer")
    public @ResponseBody String answerRequest(@RequestParam String e, String phone, String uid) {
        Set<ContactRequest> contactRequests = userRepository.findByUid(uid).getContactRequest();
        contactRequests.forEach((element) -> {
            if (element.getSender().getPhoneNumber() == phone) {
                switch (e) {
                    case "accept":
                        element.setStatus(Status.ACCEPTED);

                        break;
                    case "rejcet":
                        element.setStatus(Status.REJECTRED);
                        break;
                }

            }

        });
        return "true";

    }

    @GetMapping(path = "/all")
    public @ResponseBody ContactList getContacts(@RequestParam String uid) {
        return userRepository.findByUid(uid).getContactList();
    }

    @PostMapping(value = "/new")
    public @ResponseBody String sendRequest(@RequestParam String sendUid, String phone) {

        User sender = userRepository.findByUid(sendUid);
        User receiver = userRepository.findByPhone(phone);
        if (receiver != null) {
            ContactRequest request = new ContactRequest(sender, receiver, Status.WAITING);
            sender.setContactRequest(request);
            receiver.setContactRequest(request);
            userRepository.save(sender);
            userRepository.save(receiver);
            return "Sent friend request";
        } else
            return "No user found";
    }

}