package com.example.backend;

import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;


@Controller // This means that this class is a Controller
@RequestMapping(path = "/contacts") 
public class ContactRequestController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    
    @GetMapping(path="/requests")
    public @ResponseBody Set<ContactRequest> getContactRequests(@RequestParam String uid){
        return userRepository.findByUid(uid).getContactRequest();
    }

    @GetMapping(path="/all")
    public @ResponseBody ContactList getContacts(@RequestParam String uid){
        return userRepository.findByUid(uid).getContactList();
    }
    @PostMapping(value="/new")
    public @ResponseBody String sendRequest(@RequestBody String sendUid, String phone) {
        User sender = userRepository.findByUid(sendUid);
        User receiver  = userRepository.findByPhone(phone);
        ContactRequest request = new ContactRequest(sender, receiver);
        sender.setContactRequest(request);
        receiver.setContactRequest(request);
        userRepository.save(sender);
        userRepository.save(receiver);
        return "";
    }
    


    
}